spring:
  main:
    web-application-type: reactive
  application:
    name: issue-solver

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-headers:
              - Authorization
              - x-xsrf-token
              - Accept-language
              - Access-Control-Allow-Headers
              - Origin
              - Accept
              - X-Requested-With
              - Content-Type
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
              - Access-Control-Expose-Headers
              - X-Session-Id
              - X-Platform
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: auth-ms
          uri: https://govermentauthapi20240708181106.azurewebsites.net/
          predicates:
            - Path=/api/Auths/**
        #          filters:
        #            - StripPrefix=1

        - id: auth-ms
          uri: https://govermentauthapi20240708181106.azurewebsites.net/
          predicates:
            - Path=/api/Roles/**
        #          filters:
        #            - StripPrefix=1

        - id: auth-ms
          uri: https://govermentauthapi20240708181106.azurewebsites.net/
          predicates:
            - Path=/api/Users/**
        #          filters:
        #            - StripPrefix=1

        - id: admin-ms
          uri: https://adminapi20240708182629.azurewebsites.net/
          predicates:
            - Path=/api/Organizations/**
        #          filters:
        #            - StripPrefix=1

        - id: admin-ms
          uri: https://adminapi20240708182629.azurewebsites.net/
          predicates:
            - Path=/api/Staffs/**
        #          filters:
        #            - StripPrefix=1

        - id: request-ms
          uri: https://request-ms-d25203bd24ff.herokuapp.com/
          predicates:
            - Path=/request/**
        #          filters:
        #            - StripPrefix=0

        - id: request-ms
          uri: https://request-ms-d25203bd24ff.herokuapp.com/
          predicates:
            - Path=/category/**
        #          filters:
        #            - StripPrefix=0

        - id: request-ms
          uri: https://request-ms-d25203bd24ff.herokuapp.com/
          predicates:
            - Path=/api/v1/likes/**
        #          filters:
        #            - StripPrefix=2

        - id: request-ms
          uri: https://request-ms-d25203bd24ff.herokuapp.com/
          predicates:
            - Path=/api/v1/comments/**
#          filters:
#            - StripPrefix=2

#      default-filters:
#        - name: AddResponseHeader
#          args:
#            name: Access-Control-Allow-Origin
#            value: "*"
#        - name: AddResponseHeader
#          args:
#            name: Access-Control-Allow-Methods
#            value: "GET, PUT, POST, DELETE, OPTIONS, PATCH"
#        - name: AddResponseHeader
#          args:
#            name: Access-Control-Max-Age
#            value: "3600"
#        - name: AddResponseHeader
#          args:
#            name: Access-Control-Allow-Headers
#            value: "Authorization, x-xsrf-token, Accept-language, Access-Control-Allow-Headers, Origin, Accept, X-Requested-With, userId, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Access-Control-Expose-Headers, X-Session-Id, X-Platform"