spring:
  main:
    web-application-type: reactive
  application:
    name: issue-solver

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-headers:
              - Authorization
              - x-xsrf-token
              - Accept-language
              - Access-Control-Allow-Headers
              - Origin
              - Accept
              - X-Requested-With
              - Content-Type
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
              - Access-Control-Expose-Headers
              - X-Session-Id
              - X-Platform
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: auth-ms
          uri: https://govermentauthapi20240708181106.azurewebsites.net/
          predicates:
            - Path=/api/Auths/**


        - id: auth-ms
          uri: https://govermentauthapi20240708181106.azurewebsites.net/
          predicates:
            - Path=/api/Roles/**


        - id: auth-ms
          uri: https://govermentauthapi20240708181106.azurewebsites.net/
          predicates:
            - Path=/api/Users/**


        - id: admin-ms
          uri: https://adminapi20240708182629.azurewebsites.net/
          predicates:
            - Path=/api/Organizations/**


        - id: admin-ms
          uri: https://adminapi20240708182629.azurewebsites.net/
          predicates:
            - Path=/api/Staffs/**


        - id: request-ms
          uri: https://request-ms-d25203bd24ff.herokuapp.com/
          predicates:
            - Path=/request/**


        - id: request-ms
          uri: https://request-ms-d25203bd24ff.herokuapp.com/
          predicates:
            - Path=/category/**


        - id: request-ms
          uri: https://request-ms-d25203bd24ff.herokuapp.com/
          predicates:
            - Path=/api/v1/likes/**


        - id: request-ms
          uri: https://request-ms-d25203bd24ff.herokuapp.com/
          predicates:
            - Path=/api/v1/comments/**
